### PR TITLE
Removed footer glitch and reduced the size of the footer icons #33

### PR DESCRIPTION
**Pull request by DragonUncaged**
#33

### CODE REVIEW

**Comment by adithyapaib** [comment]
This branch has conflicts that must be resolved
Use the web editor or the  to resolve conflicts.
Conflicting files
index.html

**Comment by DragonUncaged** [comment]
Check Now !!

**Comment by adithyapaib** [comment]
Same erorr @DragonUncaged

**Comment by DragonUncaged** [comment]
Check Now !! @adithyapaib

**Comment by DragonUncaged** [comment]
I've done Please Check Now !! @adithyapaib

**Comment by adithyapaib** [comment]
> I've done Please Check Now !! @adithyapaib

Pls pr to the right branch

**Pull request closed without merging**
