### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by developerNd**
I have fix the UI but We have to redesign the Connect section

### CODE REVIEW

**Comment by adithyapaib** [comment]
This branch has conflicts that must be resolved
Use the web editor or the  to resolve conflicts.
Conflicting files
index.html

**Comment by developerNd** [comment]
conflicts resolved

**Comment by adithyapaib** [comment]
> conflicts resolved

Thanks

**Comment by developerNd** [comment]
let's solve other problems

**Pull request merged**
