### PR TITLE
In the Footer Section Social Links Email Not Working #44

### PR DESCRIPTION
**Pull request by DragonUncaged**
#44
Now when the email Icon ( @ ) is clicked it Will Open the Email address in Email App

### CODE REVIEW

**Comment by adithyapaib** [comment]
This branch has conflicts that must be resolved
Use the web editor or the  to resolve conflicts.
Conflicting files
index.html

**Comment by DragonUncaged** [comment]
Done !! Check Now

**Comment by DragonUncaged** [comment]
Check Now !! @adithyapaib

**Comment by adithyapaib** [comment]
This branch has conflicts that must be resolved
Use the web editor or the  to resolve conflicts.
Conflicting files
index.html

**Comment by DragonUncaged** [comment]
I've done Please Check Now !! @adithyapaib

**Pull request merged**
